---Q1 10 top selling products by total sales value
SELECT * 
FROM order_items
--create a new column 
ALTER TABLE order_items
ADD COLUMN total_sale FLOAT;

--updating price 
UPDATE  order_items
SET total_sale = quantity * price_per_unit;

SELECT * 
FROM order_items

--solving business problem
SELECT oi.product_id,
	   p.product_name,
	   SUM(oi.total_sale) AS  total_sales_per_product,
	   COUNT(o.order_id) AS total_orders
FROM orders o
JOIN order_items oi
ON oi.order_id = o.order_id
JOIN products p
ON p.product_id = oi.product_id
GROUP BY 1,2
ORDER BY  3 DESC
LIMIT 10
;

SELECT * FROM order_items

--Q2 Calculate total revenue generated by each product category
--include % of contribution  of each category to total_revenue

SELECT c.category_name,
	   SUM(oi.total_sale) AS Total_per_cat,
	   (SUM(oi.total_sale) / (SELECT SUM(total_sale) FROM order_items) ) * 100 AS contribution
FROM  order_items oi
JOIN products p
ON oi.product_id = p.product_id
LEFT JOIN category c 
ON p.category_id = c.category_id
GROUP BY 1
ORDER BY 2 DESC;

--Q3 Compute the average order value for each customer with including only customer have more than 5 orders
SELECT c.customer_id,
       CONCAT(c.first_name ,' ', c.last_name) AS name,
	   SUM(total_sale) /  COUNT(o.order_id) AS AOV
	   --COUNT(o.order_id) AS no_of_orders
FROM orders o
JOIN customers c
ON c.customer_id = o.customer_id
JOIN order_items oi
ON oi.order_id = o.order_id
GROUP BY 1 , 2
HAVING COUNT(o.order_id) > 5
ORDER BY 3 DESC
LIMIT 3;


--Q4 Query to Monthly total sales over the past year.
--display sales trend ,grouping by month ,return current month_sale, last month sale

SELECT 
	Month,
	Year,
	COALESCE(total_sale,0) AS current_month_sale,
	COALESCE(LAG(total_sale,1) OVER (ORDER BY Year,Month),0) AS last_month_sale
FROM ---			
(
	SELECT
		EXTRACT(YEAR FROM o.order_date) AS Year,
		EXTRACT(MONTH FROM o.order_date) AS Month,
		ROUND(SUM(oi.total_sale ::numeric),3) AS total_sale
		
	FROM orders o 
	JOIN order_items oi 
	ON o.order_id = oi.order_id
	WHERE order_date >= CURRENT_DATE - INTERVAL '1 year'
	GROUP BY 1,2
	ORDER BY 2 ,1
) AS t1

	
--Q5 Customers wit no purchases
SELECT customer_id,
	    CONCAT(first_name ,' ', last_name) AS name
FROM customers 
WHERE customer_id NOT IN (
				SELECT DISTINCT customer_id
				FROM orders
					
);

--Q6 Best-selling categories by state
--Identify the best selling product category in each state
WITH ranking_by_state 
AS(
SELECT 
	   cat.category_name,
	   c.state,
	   ROUND(SUM(oi.total_sale ::numeric),3) AS toal_sales,
	   RANK() OVER(PARTITION BY c.state ORDER BY SUM(oi.total_sale) DESC) AS Rank
FROM orders o 
JOIN customers c
ON o.customer_id = c.customer_id
JOIN order_items oi
ON o.order_id =oi.order_id
JOIN products as p
ON oi.product_id = p.product_id
JOIN category cat
ON cat.category_id = p.category_id
GROUP BY 1,2
)
SELECT * FROM ranking_by_state
WHERE rank=1;


--Q7 Calculate total  value of orders placed by each customer over their life time 
--Rank customers based on their CLTV ( customer lifetime value)
SELECT o.customer_id,
       CONCAT(c.first_name ,' ', c.last_name) AS name,
	   ROUND(SUM(oi.total_sale ::numeric),3) AS CLTV,
	   DENSE_RANK() OVER(ORDER BY SUM(oi.total_sale) DESC) AS rank	
FROM order_items oi
JOIN orders o
ON o.order_id = oi.order_id
LEFT JOIN customers c
ON o.customer_id = c.customer_id
GROUP  BY 1,2
LIMIT 5;

--Q8 Query to products with stock levels below a certain threshold (eg : less than 10 unit).
--Include last restock date and warehouse information.


SELECT p.product_name,
	   i.warehouse_id,
	   i.re_stock_date,
	   i.stock_remaining
FROM inventory i
LEFT JOIN products p
ON i.product_id = p.product_id
WHERE i.stock_remaining <10;

--Q9 Identify orders where the shipping date is later than 7 days after the order date. Include customer, order_details and delivery provider
SELECT p.product_name,
	   s.shipping_provider,
	   c.customer_id,
	   CONCAT(c.first_name ,' ', c.last_name) AS name	   
FROM shipping s
JOIN order_items oi 
    ON s.order_id = oi.order_id
JOIN orders o
	ON o.order_id = oi.order_id
JOIN customers c
	ON c.customer_id = o.customer_id
JOIN products p
    ON oi.product_id = p.product_id
WHERE s.ship_date - o.order_date >7
;


--Q10 Payment Successful rate
SELECT p.payment_status,
       COUNT(*) AS total_cnt,
	   ROUND(COUNT(*)/ (SELECT  COUNT(*) FROM payments)::numeric*100,3) AS ratio
FROM orders o
JOIN  payments p
ON o.order_id =p.order_id
GROUP BY 1;

--Q11 Top performing sellers and calculate their percentage of successful orders
WITH top_sellers AS (
    SELECT 
        s.name,
        s.seller_id,
        ROUND(SUM(oi.total_sale::numeric),3) AS total
    FROM order_items oi 
    JOIN orders o
        ON o.order_id = oi.order_id
    LEFT JOIN sellers s
        ON s.seller_id = o.seller_id
    GROUP BY s.name, s.seller_id
    ORDER BY total DESC
    LIMIT 5
),

order_status AS (
    SELECT  
        o.seller_id,
        ts.name,
        o.order_status,
        COUNT(*) AS total_orders
    FROM orders o
    JOIN top_sellers ts
        ON ts.seller_id = o.seller_id
    WHERE o.order_status NOT IN ('in_progress','refunded')
    GROUP BY o.seller_id, ts.name, o.order_status
)

SELECT 
    seller_id,
    name,
    SUM(CASE WHEN order_status = 'completed' THEN total_orders ELSE 0 END) AS completed,
    SUM(CASE WHEN order_status = 'cancelled' THEN total_orders ELSE 0 END) AS cancelled,
    SUM(total_orders) AS total_orders,
    ROUND(
        SUM(CASE WHEN order_status = 'completed' THEN total_orders ELSE 0 END)::numeric
        / SUM(total_orders)::numeric * 100, 2
    ) AS successful_ratio
FROM order_status
GROUP BY seller_id, name
ORDER BY successful_ratio DESC;

--Q12 Calculate the profit margin for each product (price-cost) ,rank products by their profit margin showing highest to lowest
SELECT oi.product_id,
	   p.product_name,
	   ROUND(SUM(total_sale::numeric - (p.cogs::numeric * oi.quantity::numeric)),3) AS profit,
	   DENSE_RANK() OVER(ORDER BY SUM(total_sale - (p.cogs * oi.quantity)) DESC) AS rank
FROM order_items oi
LEFT JOIN products p
ON p.product_id = oi.product_id
GROUP BY 1,2;

--Q13 top 10 products by the number of returns
SELECT 
    p.product_id,
    p.product_name,
    COUNT(*) AS total_sold,
    SUM(CASE WHEN s.shipping_status = 'returned' THEN 1 ELSE 0 END) AS total_return,
    ROUND(
        SUM(CASE WHEN s.shipping_status = 'returned' THEN 1 ELSE 0 END)::numeric 
        / COUNT(*)::numeric * 100,
        2
    ) AS percentage_of_return
FROM order_items oi
JOIN products p 
    ON oi.product_id = p.product_id
JOIN orders o
    ON o.order_id = oi.order_id
JOIN shipping s
    ON s.order_id = oi.order_id
GROUP BY p.product_id, p.product_name
ORDER BY total_return DESC
LIMIT 10;

--Q14 Identify sellers who havent made any payment in the last 4 months
WITH inactive_sellers AS(
	SELECT * FROM sellers
	WHERE seller_id NOT IN (SELECT seller_id FROM orders WHERE order_date >= CURRENT_DATE - INTERVAL '4 month')
)
SELECT o.seller_id,
	   MAX(o.order_date) AS last_sale_date,
	   MAX(oi.total_sale)  AS last_sale_amount
FROM orders o
JOIN inactive_sellers ins
ON ins.seller_id = o.seller_id
JOIN order_items oi
ON o.order_id = oi.order_id
GROUP BY 1;


--Q15 Identify the customers into returning or new
	--If customer has done more than 5 returns  categorize them as returning  otherwise new (customer_id,name,total_orders,total_returns)

SELECT 
	 c.customer_id,
	 CONCAT(c.first_name ,' ', c.last_name) AS customer_name,
	 COUNT(o.order_id) AS Total_orders,
	 SUM(CASE 
	 		 WHEN s.shipping_status ='returned' THEN 1
			 ELSE 0
	 	 END) AS total_returns,
     CASE 
        WHEN SUM(CASE WHEN s.shipping_status = 'returned' THEN 1 ELSE 0 END) > 5 
        THEN 'returning'
        ELSE 'new'
     END AS customer_category
	 
FROM shipping s
LEFT JOIN orders o
	ON s.order_id = o.order_id
LEFT JOIN customers c
	ON c.customer_id = o.customer_id
GROUP BY 1,2;


--Q16 Top 5 customers by orders in each state
WITH top_in_state AS
	(SELECT c.state,
		   CONCAT(c.first_name ,' ', c.last_name) AS customer_name,
		   COUNT(o.order_id) AS total_orders,
		   ROUND(SUM(oi.total_sale)::numeric,3) AS total_sale,
		   DENSE_RANK() OVER(PARTITION BY c.state ORDER BY COUNT(o.order_id) DESC) AS rank
	FROM orders as o
	JOIN order_items oi 
	ON oi.order_id = o.order_id
	JOIN customers c
	ON c.customer_id = o.customer_id
	GROUP BY 1,2
)
SELECT * FROM top_in_state
WHERE rank<=5

/*
Q17 Revenue by shipping provider.
Calculate the total revenue handled by each shipping provider.
Including the total number of orders handled and the average delivery time for each provider
*/

SELECT s.shipping_provider,
	   COUNT(o.order_id) AS total_orders,
	   SUM(oi.total_sale) AS total_revenue,
	   ROUND(AVG(s.delivery_date - s.ship_date)::numeric,0) AS average_delivery_time

FROM shipping s
LEFT JOIN order_items oi
	ON oi.order_id = s.order_id
LEFT JOIN orders o
	ON o.order_id = oi.order_id
GROUP BY 1


/*
Q18  Top 10 products with highest decreasing revenue ratio compare to last year(2024) and current year (2025)
return product_id , product_name,category name,previous year revenue and currenct year revenue decreasing ratio 
*/
WITH last_year_sale AS
(
	SELECT p.product_id,
		   p.product_name,
		   SUM(oi.total_sale) AS revenue	   
	FROM orders o
	JOIN order_items oi
		ON oi.order_id = o.order_id
	JOIN products p
		ON p.product_id = oi.product_id
	WHERE EXTRACT(YEAR FROM o.order_date) = 2024
	GROUP BY 1,2
)
,
current_year_sale
AS(
	SELECT     p.product_id,
			   p.product_name,
			   SUM(oi.total_sale) AS revenue	   
		FROM orders o
		JOIN order_items oi
			ON oi.order_id = o.order_id
		JOIN products p
			ON p.product_id = oi.product_id
		WHERE EXTRACT(YEAR FROM o.order_date) = 2025
		GROUP BY 1,2
)

SELECT cs.product_id,
	   ls.revenue AS last_year_revenue,
	   cs.revenue AS current_year_revenue,
	   ls.revenue - cs.revenue AS rev_diff,
	   ls.revenue - cs.revenue / ls.revenue * 100 AS rev_dec_ratio
	   
FROM last_year_sale ls
JOIN current_year_sale cs
ON ls.product_id = cs.product_id
WHERE ls.revenue > cs.revenue
ORDER BY 5 DESC
LIMIT 10;

/* 
Q19 Customer Retention Analysis
Identify customers who made repeat purchases within 30 days of their previous order.
*/
WITH customer_orders AS (
SELECT 
    o.customer_id,
    CONCAT(c.first_name,' ',c.last_name) AS customer_name,
    o.order_date AS first_order_date,
    LEAD(o.order_date) OVER(
        PARTITION BY o.customer_id 
        ORDER BY o.order_date
    ) AS next_order_date
FROM orders o
JOIN customers c
ON c.customer_id = o.customer_id
)

SELECT *,
       next_order_date - first_order_date AS days_between_orders
FROM customer_orders
WHERE next_order_date - first_order_date <= 30;

/*
Q20 Product Cross-Selling Analysis
Identify the top 5 product pairs that are most frequently purchased together in the same order.
*/
SELECT 
    p1.product_name AS product_1,
    p2.product_name AS product_2,
    COUNT(*) AS times_bought_together
FROM order_items oi1
JOIN order_items oi2
    ON oi1.order_id = oi2.order_id
    AND oi1.product_id < oi2.product_id
JOIN products p1
    ON oi1.product_id = p1.product_id
JOIN products p2
    ON oi2.product_id = p2.product_id
GROUP BY p1.product_name, p2.product_name
ORDER BY times_bought_together DESC
LIMIT 5;
